version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: tolarian_postgres
    environment:
      POSTGRES_DB: tolarian_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tolarian_network

volumes:
  postgres_data:
    driver: local

networks:
  tolarian_network:
    driver: bridge
